title: Tuan-Dung Bui
email: dungbuit1k28@gamil.com
description: A markdown blog made by Tuan-Dung Bui aka Zhao (zhaospei). Hosted on zhaospei.github.io. I'll write something i like maybe my study or life.
baseurl: "" 
url: "https://zhaospei.github.io/" 
twitter_username: zhaospei
github_username:  zhaospei
author: Tuan-Dung Bui
language: vi

timezone: Asia/Bangkok

google_analytics: 'G-HSCBJBJKGQ'

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-postcss
  - jemoji

postcss:
  cache: false

collections:
  authors:
    output: true
  projects:
    output: false

feed:
  path: ./feed.xml

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      toc: true


exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
